# Generated by Django 5.0.6 on 2024-06-15 06:28

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defining_niche', models.JSONField(blank=True, default=dict)),
                ('voluem_market', models.JSONField(blank=True, default=dict)),
                ('list_key_players', models.JSONField(blank=True, default=dict)),
                ('list_key_consumers', models.JSONField(blank=True, default=dict)),
                ('list_common_products', models.JSONField(blank=True, default=dict)),
                ('trends_niche', models.JSONField(blank=True, default=dict)),
                ('resume_niche', models.JSONField(blank=True, default=dict)),
                ('date_create', models.DateTimeField(default=datetime.datetime.now)),
                ('is_active', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
