# Generated by Django 5.0.6 on 2024-06-15 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportapp', '0002_template_reportresult_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportresult',
            name='resume_niche',
        ),
        migrations.RemoveField(
            model_name='reportresult',
            name='trends_niche',
        ),
    ]
